{"uuid": "bf3e709f-6bee-4d13-9ac4-6e44ef4b4e33", "children": ["d989d7a7-edbd-4fc3-8cd7-dcddedba6b0a", "1ecbef70-5053-47eb-a14e-f81c2d47091a", "0b15b82c-55e6-4355-8eca-df83a17ffba8", "e2bfef73-fc70-4604-8a98-4d186cfd4363", "1cccbc09-5cc8-485e-86f9-64dfee4b0b3c", "7ae89ff4-d425-4592-ab4b-9e98ee368422"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'tests' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"C:\\Users\\Pavan\\AppData\\Local\\Programs\\Python\\Python37-32\\Amazon_Python_Automation\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Pavan\\AppData\\Local\\Programs\\Python\\Python37-32\\Amazon_Python_Automation\\lib\\site-packages\\_pytest\\fixtures.py\", line 935, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Pavan\\AppData\\Local\\Programs\\Python\\Python37-32\\Amazon_Python_Automation\\lib\\site-packages\\_pytest\\fixtures.py\", line 794, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"E:\\Gyan_Matrix\\Amazon_Python_Automation\\conftest.py\", line 14, in test_setup\n    driver = webdriver.Chrome(executable_path=dr.chrome_driver)\n  File \"C:\\Users\\Pavan\\AppData\\Local\\Programs\\Python\\Python37-32\\Amazon_Python_Automation\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"C:\\Users\\Pavan\\AppData\\Local\\Programs\\Python\\Python37-32\\Amazon_Python_Automation\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 88, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1555411117095, "stop": 1555411117097}], "start": 1555411117095, "stop": 1555411118994}